### PR TITLE
Scrape timestamp from new VF website format

### LINKED ISSUE #8: Invalid Date Returned
Dears,

We are running the API on a google cloud instance, and we're able to call it without any problems.
Suddenly this afternoon the returns started to come with an "Invalid Date" 

{
  "error": null,
  "data": {
    "timestamp": "Invalid Date",
    "unixtime": null,
    "latitude": 39.86164,
    "longitude": -0.06943,
    "course": 88,
    "speed": 0
  }
}
Is there anything wrong with our settings?

### PR DESCRIPTION
**Pull request by curiousleo**
Fixes one half of #8: scraping from the new VF website. Scraping MT is still broken, and needs to be addressed in a separate PR.

**Before**
```
$ node index.js 
Node app is running on port 5000
getLocationFromVF https://www.vesselfinder.com/vessels/somestring-MMSI-211281610
Extracted:  39.86162 N/0.06946 W  0.0 261.0
Position:  { error: null,
  data:
   { timestamp: 'Invalid Date',
     unixtime: NaN,
     course: '261.0',
     speed: '0.0',
     latitude: 39.86162,
     longitude: -0.06946 } }
```

**After**
```
$ node index.js 
Node app is running on port 5000
getLocationFromVF https://www.vesselfinder.com/vessels/somestring-MMSI-211281610
Extracted:  39.86162 N/0.06946 W  0.0 261.0
Position:  { error: null,
  data:
   { timestamp:
      'Thu Jan 30 2020 22:30:00 GMT+0100 (Central European Standard Time)',
     unixtime: 1580419800,
     course: '261.0',
     speed: '0.0',
     latitude: 39.86162,
     longitude: -0.06946 } }
```

### CODE REVIEW

File: api.js [hunk 1]
```diff
@@ -69,8 +69,8 @@ function getLocationFromVF(mmsi, cb) {
       const latitude = splitted[0].indexOf('N') === -1 ? parseFloat(splitted[0]) * -1 : parseFloat(splitted[0]);
       const longitude = splitted[1].indexOf('E') === -1 ? parseFloat(splitted[1]) * -1 : parseFloat(splitted[1]);
 
-      const timestamp = new Date($('.vfix-top:nth-of-type(1) .tparams tr:nth-of-type(11) .v3').text()).toString();
-      const unixtime = new Date($('.vfix-top:nth-of-type(1) .tparams tr:nth-of-type(11) .v3').text()).getTime()/1000;
+      const timestamp = new Date($('#lastrep').attr('data-title')).toString();
```
Comment (curiousleo) [inline api.js]: The relevant `<td>` tag has the `#lastrep` ID. IDs are unique, so this seems like a more straightforward way of querying for the right element.

From https://www.vesselfinder.com/vessels/FSO-ASIA-IMO-9224752-MMSI-538003426:

```html
<td class="v3 tooltip expand" data-title="Jan 30, 2020 20:56 UTC" id="lastrep">
    <span class="">40 mins ago </span>
    <span class="info"><i>i</i></span>
</td>
```

File: api.js [hunk 2]
```diff
@@ -69,8 +69,8 @@ function getLocationFromVF(mmsi, cb) {
...
+      const unixtime = new Date(timestamp).getTime()/1000;
```
Comment (curiousleo) [inline api.js]: No need to perform another query here - we already have the timestamp!

Comment (camende) [reply api.js]: That certainly seems to fix the Vesselfinder scraping... but not the marine traffic (yet) this returns only could not parse date.

The date seems to be here:
image

What would need to be changed in the API code to pull the date/time from MT as well ?

**Comment by curiousleo** [comment]
@camende wrote:
> That certainly seems to fix the Vesselfinder scraping... but not the marine traffic (yet) this returns only could not parse date.

The changes to MT are more involved because that website is essentially an app now, which loads data from an internal API after the website itself has been served. My proposal would be to separate that out into another PR.

**Comment by curiousleo** [comment]
Yeah, so scraping from MT is going to be difficult. There's a `Vessel-Image` header sent along with every API request. AFAICT it's some sort of hash based on various browser properties as well as the request. So the `Vessel-Image` required for each MMSI will be different.

I see two approaches: (1) reverse-engineer the hash - daunting; (2) run an actual browser for each request, let it render the page and then scrape it - this is slow/computationally expensive.

For illustration, this is some of the code that computes the `Vessel-Image` header content:

```javascript
    }, 1649: function (e, t, n) {
      'use strict';
      Object.defineProperty(t, '__esModule', {
        value: !0
      }),
      t.default = function () {
        (0, r.getFingeprint) ().then(function (e) {
          a.default.defaults.headers.common['Vessel-Image'] = e,
          $.ajaxSetup({
            beforeSend: function (t) {
              t.setRequestHeader('Vessel-Image', e)
            }
          })
        })
      };
      var i,
      a = (i = n(339)) && i.__esModule ? i : {
      default:
        i
      },
      r = n(1650)
    },
    1650:
    function (e, t, n) {
      'use strict';
      Object.defineProperty(t, '__esModule', {
        value: !0
      }),
      t.getFingeprint = void 0;
      var i,
      a = (i = n(1651)) && i.__esModule ? i : {
      default:
        i
      };
      t.getFingeprint = function () {
        return new Promise(function (e, t) {
          (new a.default).get(function (n) {
            n || t(new Error('Fingerprint is not detected')),
            s().then(function (t) {
              o(t).then(function (t) {
                e(t + n + r(n))
              })
            })
          })
        })
      };
      var r = function (e) {
        var t = (parseInt(e.substring(0, 6), 16) % e.length).toString();
        return 1 === t.length && (t = '0' + t),
        t
      },
      o = function (e) {
        return new Promise(function (t, n) {
          var i;
          1 === e.length && (i = '0' + e),
          i ? t(i)  : n(new Error(''))
        })
      },
      s = function () {
        return new Promise(function (e, t) {
          var n = !1,
          i = !1,
          a = !1,
          r = !1,
          o = !1,
          s = window.navigator.vendor,
          l = window.navigator.userAgent.indexOf('OPR') > - 1,
          c = window.navigator.userAgent.indexOf('Edge') > - 1;
          window.navigator.userAgent || (n = !0),
          'function' != typeof window.callPhantom && 'function' != typeof window._phantom || (o = !0),
          navigator.webdriver && (a = !0),
          'Google Inc.' === s && !1 === l && !1 === c && !window.chrome && (r = !0),
          void 0 !== navigator.permissions && navigator.permissions.query({
            name: 'notifications'
          }).then(function (t) {
            'denied' === Notification.permission && 'prompt' === t.state && e(i = !0)
          });
          var u,
          d = (u = [
            n,
            o,
            i,
            r,
            a
          ], new Promise(function (e, t) {
            var n = [
            ],
            i = u,
            a = Array.isArray(i),
            r = 0;
            for (i = a ? i : i[Symbol.iterator](); ; ) {
              var o;
              if (a) {
                if (r >= i.length) break;
                o = i[r++]
              } else {
                if ((r = i.next()).done) break;
                o = r.value
              }
              var s = o;
              n.push(!0 === s ? 1 : 0)
            }
            var l = parseInt(function (e) {
              var t = '',
              n = e,
              i = Array.isArray(n),
              a = 0;
              for (n = i ? n : n[Symbol.iterator](); ; ) {
                var r;
                if (i) {
                  if (a >= n.length) break;
                  r = n[a++]
                } else {
                  if ((a = n.next()).done) break;
                  r = a.value
                }
                t += r.toString()
              }
              return t
            }(n), 2).toString(10);
            l ? e(l)  : t(new Error('Decimal from Binary failed'))
          }));
          d ? e(d)  : t(new Error('Browser properties are not detected'))
        })
      }
    },
```
